sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - yarn lint
  - yarn test --coverage
after_success:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
